title: Hunter's SpaceTime
author: teslatickles
email: hunterhartline@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A place to stay, for as long as you can. Cat tech and video games. 
 Put the knowledge into your brain.
 
# social links
twitter_username: your-twitter-handle
github_username:  teslatickles

show_excerpts: true # set to false to remove excerpts on the homepage

theme: modirna
